import Providers from "@/components/core/providers";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import { Bell, Menu as MenuIcon } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import Menu from "./components/menu";
import "./globals.css";

// export const runtime = "edge";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <Providers>
          <Toaster position="top-center" closeButton theme="system" />
          <header className="flex items-center justify-between p-3 border-b shadow sticky top-0 bg-background/90 backdrop-blur ">
            <Button variant={"ghost"} size={"icon"}>
              <MenuIcon />
            </Button>
            <Link href={"/"}>
              <h1 className="font-bold">Marketplace</h1>
            </Link>
            <div className="flex">
              <Button variant={"ghost"} size={"icon"}>
                <Bell />
              </Button>
              <div className="hidden md:block">
                <Menu />
              </div>
            </div>
          </header>
          <main className="p-3   min-h-[calc(100svh-120px)]">{children}</main>
          <footer className="border-top border md:hidden shadow p-3 sticky bottom-0 bg-background/90 backdrop-blur ">
            <Menu />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
